project:
  type: website
  resources:
    - "CNAME"
    - "*.pdf"
  render:
    - "*.qmd"
    - "!*_template.qmd"
  preview:
    port: 7878
    browser: false # setting it for my convenience cause I prefer to refresh the same tab

website:
  title: "WOMBAT 2026 – Data Science & Analytics Workshop"
  site-url: "https://wombat2026.numbat.space"
  sidebar: false
  search: false
  favicon: img/wombat/wombat-pixelart.svg
  open-graph:
    image: /img/opengraph-banner.jpg
    image-width: 1200
    image-height: 630
  twitter-card:
    image: /img/opengraph-banner.jpg
    card-style: summary_large_image

  # announcement: 
  #   icon: megaphone-fill
  #   dismissable: true
  #   content: "Save the date: Nov 30 - Dec 1 for WOMBAT 2026!"
  #   type: success
  #   position: below-navbar
    
  navbar:
    title: "WOMBAT"
    background: light
    pinned: true
    collapse-below: sm
    toggle-position: right
    right:
      - text: Schedule
        href: program/schedule
      - text: Contact
        href: contact.qmd
      - text: About
        menu:
          - text: Code of Conduct
            href: participation/coc.qmd
          - text: Organising Committee
            href: about/committee
      - text: Register
        href: participation/register.qmd
      - text: Live Program
        href: live.qmd
  page-footer: 
    left: "Workshop Organised by the Monash Business Analytics Team"
    right: 
      - icon: globe
        href: https://numbat.space
      - icon: github
        href: https://github.com/numbats
      - icon: envelope
        href: mailto:buseco-ebs.wombat@monash.edu

format:
  html:
    theme: 
      light: [css/theme.scss]
      #dark: darkly
    page-layout: custom
    toc: false
    canonical-url: true
    include-after-body:
      - plausible.html
      - js/hero-navbar.html
      - js/hero-wave.html
      - js/live-status.html

# editor: visual

